name: KONG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/4 * * *"
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  KONG:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Get KONG
        run: |
          git clone https://${{ secrets.KONG_REPO_PAT }}@github.com/statsig-io/kong.git .

      - name: Install Deps
        run: npm install

      - name: Setup .NET SDK
        run: npm run kong -- setup dotnet -v

      - name: Build Bridge
        run: npm run kong -- build dotnet -v

      - name: Run Tests
        run: npm run kong -- test dotnet -v -r
